Us07 - crud de postos de trabalho
fga-eps-mds/2022-2-schedula-gerenciador-de-localidades pull request #9
Opened 2023-01-17 19:58 UTC by PedroFMuniz

# Pull Request

## 📖 Description

CRUD for workstations and related tests done and working.

closes fga-eps-mds/2022-2-Schedula-Doc#36

### 🎫 Issues

## 👩‍💻 Reviewer Notes

## 📑 Test Plan

## ⏭ Next Steps

2023-01-18 17:48 UTC, kleidson-alves requested changes

2023-01-18 17:48 UTC, kleidson-alves commented on src/workstations/workstations.controller.spec.ts
> +  describe('findWorkspace', () => {
A descrição do teste não deveria ser findWorkstation? Isso vale para todos as outras descrições depois dessa

2023-01-18 17:48 UTC, kleidson-alves commented on src/workstations/workstations.controller.ts
> +    const options = JSON.parse(request.headers['response_fields']);
Trocar a abordagem para não haver um header na requisição

2023-01-18 18:01 UTC, PedroFMuniz commented on src/workstations/workstations.controller.spec.ts
> +  describe('findWorkspace', () => {
Sim, foi uma confusão, já alterei as ocorrências

2023-01-18 18:01 UTC, PedroFMuniz commented on src/workstations/workstations.controller.ts
> +    const options = JSON.parse(request.headers['response_fields']);
Header removido

2023-01-18 19:55 UTC, kleidson-alves approved these changes

2023-01-19 11:59 UTC, kleidson-alves approved these changes

2023-01-19 12:05 UTC, merged